# Generated by Django 4.2 on 2023-04-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APICreditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbcreditos',
            table='TbCreditos',
        ),
    ]
