# Generated by Django 4.2 on 2023-04-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIProfesor', '0003_rename_apedocente_tbprofesor_apellidodocente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbEstado',
            fields=[
                ('IdEstado', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbestado',
            },
        ),
        migrations.CreateModel(
            name='TbCursos',
            fields=[
                ('CodigoCurso', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCurso', models.CharField(max_length=255)),
                ('THCurso', models.PositiveIntegerField()),
                ('PreRequisitoCurso', models.PositiveIntegerField()),
                ('CicloCurso', models.CharField(max_length=255)),
                ('CodigoDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIProfesor.tbprofesor')),
                ('TbEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APICursos.tbestado')),
            ],
            options={
                'db_table': 'TbCursos',
            },
        ),
    ]
