# Generated by Django 4.2 on 2023-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APICursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcursos',
            name='CodigoCurso',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='tbestado',
            table='TbEstado',
        ),
    ]
