# Generated by Django 4.2 on 2023-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APICursos', '0002_alter_tbcursos_codigocurso_alter_tbestado_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcursos',
            name='PreRequisitoCurso',
            field=models.CharField(max_length=255),
        ),
    ]
