# Generated by Django 4.2 on 2023-04-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APICursos', '0003_alter_tbcursos_prerequisitocurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbcursos',
            old_name='CodigoDocente',
            new_name='CodigoDocente_id',
        ),
        migrations.RenameField(
            model_name='tbcursos',
            old_name='TbEstado',
            new_name='TbEstado_id',
        ),
    ]
