# Generated by Django 4.2 on 2023-04-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APICursos', '0004_rename_codigodocente_tbcursos_codigodocente_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbcursos',
            old_name='CodigoDocente_id',
            new_name='CodigoDocente',
        ),
        migrations.RenameField(
            model_name='tbcursos',
            old_name='TbEstado_id',
            new_name='TbEstado',
        ),
    ]
