# Generated by Django 4.2 on 2023-04-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APICursos', '0005_rename_codigodocente_id_tbcursos_codigodocente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbcursos',
            old_name='CodigoDocente',
            new_name='CodigoProfesor',
        ),
    ]
