# Generated by Django 4.2 on 2023-04-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APICursos', '0006_rename_codigodocente_tbcursos_codigoprofesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbcursos',
            old_name='TbEstado',
            new_name='FkEstado',
        ),
    ]
