# Generated by Django 4.2 on 2023-04-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('CodCredito', models.AutoField(primary_key=True, serialize=False)),
                ('TipCredito', models.CharField(max_length=50)),
            ],
        ),
    ]
