# Generated by Django 4.2 on 2023-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('CodDocente', models.AutoField(primary_key=True, serialize=False)),
                ('NomDocente', models.CharField(max_length=50)),
                ('ApeDocente', models.CharField(max_length=50)),
                ('EmaDocente', models.CharField(max_length=50)),
                ('NumDocente', models.PositiveIntegerField()),
                ('DirDocente', models.CharField(max_length=50)),
            ],
        ),
    ]
