# Generated by Django 4.2 on 2023-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbProfesor',
            fields=[
                ('CodigoProfesor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProfesor', models.CharField(max_length=50)),
                ('ApellidoProfesor', models.CharField(max_length=50)),
                ('EmailProfesor', models.CharField(max_length=50)),
                ('NumeroProfesor', models.PositiveIntegerField()),
                ('DireccionProfesor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TbProfesor',
            },
        ),
    ]
