# Generated by Django 4.2 on 2023-04-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIProfesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbprofesor',
            table='TbProfesor',
        ),
    ]
