# Generated by Django 4.2 on 2023-04-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIProfesor', '0002_alter_tbprofesor_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbprofesor',
            old_name='ApeDocente',
            new_name='ApellidoDocente',
        ),
        migrations.RenameField(
            model_name='tbprofesor',
            old_name='CodDocente',
            new_name='CodigoDocente',
        ),
        migrations.RenameField(
            model_name='tbprofesor',
            old_name='DirDocente',
            new_name='DireccionDocente',
        ),
        migrations.RenameField(
            model_name='tbprofesor',
            old_name='EmaDocente',
            new_name='EmailDocente',
        ),
        migrations.RenameField(
            model_name='tbprofesor',
            old_name='NomDocente',
            new_name='NombreDocente',
        ),
        migrations.RenameField(
            model_name='tbprofesor',
            old_name='NumDocente',
            new_name='NumeroDocente',
        ),
    ]
