# Generated by Django 4.2 on 2023-04-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APICursos', '0001_initial'),
        ('APICreditos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDetalleCredito',
            fields=[
                ('CodigoDetalleCredito', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveIntegerField(max_length=255)),
                ('CodigoCredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APICreditos.tbcreditos')),
                ('CodigoCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APICursos.tbcursos')),
            ],
            options={
                'db_table': 'TbDetalleCredito',
            },
        ),
    ]
