# Generated by Django 4.2 on 2023-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDetalleCreditos', '0002_alter_tbdetallecredito_codigodetallecredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdetallecredito',
            name='Cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
